---
- name: Ensure that Apache is installed
  apt: name=apache2 state=present

- name: Start Apache
  service: name=apache2 state=started enabled=yes

- name: Deploy configuration File
  template: src=apache2.j2 dest=/etc/apache2/conf-available/apache2.conf # Remember that templates/ is not needed
  notify:
    - Restart Apache

- name: Copy Site Files
  template: src=index.j2 dest={{ doc_root }}/index.html